name: My CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: python.exe -m pip install -r requirements.txt

      - name: Run tests
        run: |
          cd ..
          pytest --cov=.
        #curl -X POST -H "Content-Type: application/json" -d "{\"1331277451\": \"1331277451\", \"text\": \"Build started!\"}" \https://api.telegram.org/bot<7705354270:AAGKM_nf8lN12S7SZ90jcCkRl1Cr5bMzzC0>/sendMessage
          

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          #to: ${{ secrets.TELEGRAM_CHAT_ID }}
          to: 1331277451
          #token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          token: 7705354270:AAGKM_nf8lN12S7SZ90jcCkRl1Cr5bMzzC0
          message: |
            Build status for ${{ github.repository }}:
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Event: ${{ github.event_name }}
            Status: ${{ job.status }}    
        #when: on_success

