name: My CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: python.exe -m pip install -r requirements.txt

      - name: Run tests
        run: |
          cd ..
          pytest --cov=.
          curl -X POST -H "Content-Type: application/json" -d "{\"chat_id\": \"1331277451\", \"text\": \"Build started!\"}" \ https://api.telegram.org/bot7705354270:AAGKM_nf8lN12S7SZ90jcCkRl1Cr5bMzzC0/sendMessage

